import type { Metadata } from "next";
import { Geist, Geist_Mono, Crete_Round, Work_Sans } from "next/font/google";
import Navbar from "./components/navbar";
import "./globals.css";
import { ChildProps } from "@/types";

const creteRound = Crete_Round({
  weight: ["400"],
  subsets: ["latin"],
  variable: '--font-creteRound'
});

const workSans = Work_Sans({
  weight: ['500', '600'],
  subsets: ["latin"],
  variable: '--font-workSans'
});

export const metadata: Metadata = {
  title: "Blog App",
  description: "Generated by create next app",
};

function RootLayout({ children }: ChildProps ) {
  return (
    <html lang="en">
      <body
        className={`${creteRound.variable} ${workSans.variable} antialiased`}
      >
        <Navbar />
        {children}
      </body>
    </html>
  );
}

export default RootLayout;